# -*- mode: python ; coding: utf-8 -*-
# 优化要点（针对启动速度）：
#   1. onedir 模式（COLLECT 段）— 避免 onefile 解压到 /tmp 的时间
#   2. upx=False — UPX 运行时解压会显著拖慢启动
#   3. excludes 排除所有未使用的 Qt 模块 — 减小体积、减少动态库加载时间

a = Analysis(
    ['cangui.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('cangui/logo.svg', 'cangui'),
        ('cangui/check.svg', 'cangui'),
        ('cangui/logo.ico', 'cangui'),
    ],
    hiddenimports=[
        'usb.backend.libusb1',
        'PySide6.QtXml',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # —— 未使用的 Qt 模块（按字母顺序）——
        'PySide6.Qt3DAnimation',
        'PySide6.Qt3DCore',
        'PySide6.Qt3DExtras',
        'PySide6.Qt3DInput',
        'PySide6.Qt3DLogic',
        'PySide6.Qt3DRender',
        'PySide6.QtBluetooth',
        'PySide6.QtCharts',
        'PySide6.QtConcurrent',
        'PySide6.QtDBus',
        'PySide6.QtDataVisualization',
        'PySide6.QtDesigner',
        'PySide6.QtGraphs',
        'PySide6.QtGraphsWidgets',
        'PySide6.QtHelp',
        'PySide6.QtHttpServer',
        'PySide6.QtLocation',
        'PySide6.QtMultimedia',
        'PySide6.QtMultimediaWidgets',
        'PySide6.QtNetwork',
        'PySide6.QtNetworkAuth',
        'PySide6.QtNfc',
        'PySide6.QtOpenGL',
        'PySide6.QtOpenGLWidgets',
        'PySide6.QtPdf',
        'PySide6.QtPdfWidgets',
        'PySide6.QtPositioning',
        'PySide6.QtQml',
        'PySide6.QtQuick',
        'PySide6.QtQuick3D',
        'PySide6.QtQuickControls2',
        'PySide6.QtQuickTest',
        'PySide6.QtQuickWidgets',
        'PySide6.QtRemoteObjects',
        'PySide6.QtScxml',
        'PySide6.QtSensors',
        'PySide6.QtSerialBus',
        'PySide6.QtSerialPort',
        'PySide6.QtSpatialAudio',
        'PySide6.QtSql',
        'PySide6.QtStateMachine',
        'PySide6.QtTest',
        'PySide6.QtTextToSpeech',
        'PySide6.QtUiTools',
        'PySide6.QtWebChannel',
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebEngineQuick',
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtWebSockets',
        'PySide6.QtWebView',
        # —— 其它未使用的标准库模块 ——
        'tkinter',
        'unittest',
        'pydoc',
        'doctest',
        'pdb',
        'lib2to3',
        'distutils',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='CANable2.5',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=False,                  # 关闭 UPX：启动更快
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['cangui/logo.ico'],
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip_binaries=True,
    upx=False,                  # 关闭 UPX：启动更快
    upx_exclude=[],
    name='CANable2.5',
)
